Display Courses and add Courses (#20)
* Course card, no progress bar yet, added scrollable, need to fix styles

* Created Course Card (and Assessment)

* Added DialogModal component

* Added switch ui

* Added fields naming scheme, made dialog a wrapper, finished switch

* Added partial add course form, update field folder

* Added react select, updated schema

* Created wrapper

* Made a preliminary functioning select that works on Radix forms

* part of last commit

* Implemented SelectDropdown and FormSelect

* Align switch button with input fields

* Completed Add Course

* Fix TypeError: bufferUtil.mask is not a function error on Vercel